name: qreo
description: "A new Flutter project."
# aplicacion para gestion de pagos con qr
# conectadas a mi cuenta de supabase
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  supabase_flutter: ^2.8.4
  provider: ^6.1.4
  flutter_tabler_icons: ^1.37.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.4
  loading_indicator: ^3.1.1
  overlay_loading_progress: ^1.0.1
  image_picker: ^1.1.2
  intl: ^0.17.0
  curved_navigation_bar: ^1.0.6
  scaler: ^1.1.2+1
  flutter_custom_month_picker: ^0.1.3
  cloud_firestore: ^4.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/imagenes/